import Foundation

/// 条目「种类」本地化名称 (预览窗口的"种类"列,对齐 FastZip 观感)。
public enum ArchiveKind {
    /// 依据名称后缀推断可读类型名;未知时回退为「XXX 文件」。
    public static func displayName(forName name: String, isDirectory: Bool) -> String {
        if isDirectory { return "文件夹" }
        let ext = (name as NSString).pathExtension.lowercased()
        switch ext {
        case "": return "文稿"
        case "png": return "PNG 图像"
        case "jpg", "jpeg": return "JPEG 图像"
        case "gif": return "GIF 图像"
        case "heic", "heif": return "HEIF 图像"
        case "tiff", "tif": return "TIFF 图像"
        case "bmp": return "BMP 图像"
        case "webp": return "WebP 图像"
        case "svg": return "SVG 图像"
        case "icns": return "图标"
        case "mp4", "m4v": return "MPEG-4 影片"
        case "mov": return "QuickTime 影片"
        case "avi": return "AVI 影片"
        case "mkv": return "Matroska 影片"
        case "webm": return "WebM 影片"
        case "flv": return "Flash 影片"
        case "wmv": return "Windows 媒体影片"
        case "mp3": return "MP3 音频"
        case "wav": return "WAV 音频"
        case "aac": return "AAC 音频"
        case "flac": return "FLAC 音频"
        case "m4a": return "Apple 音频"
        case "aiff": return "AIFF 音频"
        case "ogg": return "Ogg 音频"
        case "pdf": return "PDF 文稿"
        case "txt", "log", "text": return "纯文本"
        case "md", "markdown": return "Markdown 文稿"
        case "rtf": return "RTF 文稿"
        case "sql": return "SQL 文稿"
        case "json": return "JSON 文稿"
        case "xml": return "XML 文稿"
        case "html", "htm": return "HTML 文稿"
        case "css": return "CSS 样式表"
        case "yml", "yaml": return "YAML 文稿"
        case "csv": return "CSV 表格"
        case "doc": return "Word 文稿"
        case "docx": return "Word 文稿"
        case "pages": return "Pages 文稿"
        case "xls": return "Excel 表格"
        case "xlsx": return "Excel 表格"
        case "numbers": return "Numbers 表格"
        case "ppt": return "PowerPoint 演示文稿"
        case "pptx": return "PowerPoint 演示文稿"
        case "key": return "Keynote 演示文稿"
        case "zip": return "ZIP 压缩包"
        case "7z": return "7Z 压缩包"
        case "rar": return "RAR 压缩包"
        case "tar": return "TAR 归档"
        case "gz", "tgz": return "GZIP 归档"
        case "bz2", "tbz": return "BZIP2 归档"
        case "xz", "txz": return "XZ 归档"
        case "dmg": return "磁盘映像"
        case "pkg": return "安装包"
        case "app": return "应用程序"
        case "sh", "bash", "zsh": return "Shell 脚本"
        case "py": return "Python 脚本"
        case "js": return "JavaScript 脚本"
        case "ts": return "TypeScript 脚本"
        case "java": return "Java 源代码"
        case "c", "h": return "C 源代码"
        case "cc", "cpp", "hpp", "cxx": return "C++ 源代码"
        case "swift": return "Swift 源代码"
        case "go": return "Go 源代码"
        case "rs": return "Rust 源代码"
        case "rb": return "Ruby 脚本"
        default:
            return "\(ext.uppercased()) 文件"
        }
    }
}
